[package]
name = "driver-verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
kernel = { path = "/lib/modules/$(shell uname -r)/build/rust" }

[features]
default = []
